# Generated by Django 5.2.2 on 2025-06-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='co_supervisors',
            field=models.ManyToManyField(blank=True, related_name='co_supervised_students', to='fses.lecturer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OFFICE_ASSISTANT', 'Office Assistant'), ('SUPERVISOR', 'Supervisor'), ('PROGRAM_COORDINATOR', 'Program Coordinator'), ('PGAM', 'PGAM')], default='SUPERVISOR', max_length=20),
        ),
    ]
